name: mega_flutter_network
description: A new Flutter package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.3
  dio: ^4.0.6
  flutter_modular: ^5.0.3
  ua_client_hints: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^1.0.3
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11

  mega_flutter_base:
    path: ../mega_flutter_base

  megaleios_flutter_localization:
    path: ../megaleios_flutter_localization
  diacritic: ^0.1.3
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true