name: mega_flutter_services
description: A new Flutter package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clipboard: ^0.1.3
  file_picker: ^8.3.6
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  flutter_modular: ^5.0.3
  geocoding: ^2.0.5
  geolocator: ^10.1.0
  google_maps_flutter: ^2.2.2
  google_sign_in: ^5.4.2
  image_picker: ^1.0.4
  onesignal_flutter: ^5.2.9
  permission_handler: ^10.4.3
  url_launcher: ^6.1.7
  share_plus: ^10.1.4
  external_path: ^1.0.3
  path_provider: ^2.0.11
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_image_compress: ^2.1.0

  megaleios_flutter_localization:
    path: ../megaleios_flutter_localization

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
