name: mega_flutter_base
description: A new Flutter package.
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_pattern: ^3.0.1
  email_validator: ^2.1.17
  strings: ^0.2.2
  connectivity_plus: ^6.1.3
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^5.0.3
  font_awesome_flutter: ^10.3.0
  mask_text_input_formatter: ^2.4.0
  modal_progress_hud_nsn: ^0.3.0
  rxdart: ^0.27.7

  mega_flutter_components:
    path: ../mega_flutter_components

  mega_flutter_network:
    path: ../mega_flutter_network

  megaleios_flutter_localization:
    path: ../megaleios_flutter_localization
  validatorless: ^1.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
